### ISSUE TITLE
Weather cycle

### ISSUE THREAD

**Issue by felix-schindler** [kida31/untitled-plant-game#13]
Add weather cycle (sunny and rain) that changes with time

> From our Notion:
> - **Sunny**
> - **Rain**
> - Clouded
> - Snow

## TODOs

- [x] Es gibt sonnige Tage
- [x] Es gibt Regentage
- [ ] Doku wie es funktioniert in Notion
