### ISSUE TITLE
Map / Main scene

### ISSUE THREAD

**Issue by felix-schindler** [kida31/untitled-plant-game#60]
Wir brauchen eine Map. Diese muss einige Sachen beinhalten

- [ ] Grundlegender Boden (Gras oder so)
- [ ] #68 Einem Haus
- [ ] #67 und Garten
- [ ] Platz wo man Dinge anpflanzen kann
- [ ] Vending machine
  - [ ] mit der man interagieren kann
- [ ] Seed shop
  - [ ] mit dem interagieren kann
- [ ] NPCs
  - [ ] die herumlaufen
  - [ ] mit denen man reden kann
- [ ] Teich
  - [ ] in dem man angeln kann
- [ ] Ein Spieler
  - [ ] mit custom Textur
  - [ ] den man bewegen kann
  - [ ] dem die Kamera folgt
    - [ ] within Scene Constraints

**Comment by Sui-nyan** [comment]
#68 #67
